### ISSUE TITLE
Create CONTRIBUTION GUIDELINE Page

### ISSUE THREAD

**Issue by JinnaBalu** [JinnaBalu/bootstrap-pages#2]
Add contribution guidelines page.

**Comment by igavelyuk** [comment]
I will take this task:
- [ ] Update existing CONTRIBUTION.md
The following sections will be added:
* Getting Started 
* Claiming an Issue
* Resolving an Issue
* Creating a Pull Request

**Comment by igavelyuk** [comment]
The file name will be CONTRIBUTION GUIDELINE.md, not  CONTRIBUTION.md

**Comment by JinnaBalu** [comment]
CONTRIBUTION-GUIDELINES.md

**Comment by Ri2parna** [comment]
is it still open?
